version: 1.0.{build}

image:
- Visual Studio 2019 Preview

platform:
- x86
- x64

configuration:
- Debug
- Release

before_build:
- md build

build_script:
- if %platform%==x86 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvars32.bat"
- if %platform%==x64 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvars64.bat"
- cmake -B build/%platform% -G Ninja

test_script:
- cmake --build build/%platform% --target koru-tests --config %configuration%

matrix:
  fast_finish: true